name: Build site

on:
  push:
    branches: [ main, master, build-github-action ]
    paths-ignore: 'build'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Update submodules
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "noreply@example.com"
          git submodule update --remote --recursive
      - name: Set up Ruby 3.2
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: "3.2"
      - name: Install dependencies
        run: bundle install

      - name: Run middleman
        run: bundle exec middleman build --verbose || exit 0  # Build probably will have errors

      - name: Make build/docs not a submodule
        run: rm -rf build/docs/.git || exit 0

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "build"

  deploy:
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

